-- Complete RideFlow Showroom Setup Script
-- Run this in Supabase Dashboard -> SQL Editor

-- 1. Create Core Tables
CREATE TABLE IF NOT EXISTS public.inventory (
  id bigint generated by default as identity primary key,
  model text not null,
  variant text,
  cc integer,
  color text,
  ex_showroom_price numeric,
  on_road_price numeric,
  max_discount numeric,
  stock integer not null default 1,
  stock_by_color jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  aadhaar_last4 text,
  pan_masked text,
  aadhaar_document_path text,
  pan_document_path text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id),
  customer_name text not null,
  customer_phone text,
  vehicle_id bigint references public.inventory(id),
  vehicle_name text not null,
  original_price numeric,
  discount numeric,
  sale_amount numeric,
  payment_status text,
  sale_type text default 'Sale',
  old_vehicle_name text,
  old_vehicle_registration text,
  exchange_discount numeric default 0,
  exchange_value numeric default 0,
  emi_amount numeric,
  tenure_months integer,
  amount_paid numeric default 0,
  signature_data text,
  invoice_number text,
  rc_photo_path text,
  sale_date timestamptz default now(),
  updated_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.test_drive_inventory (
  id bigint generated by default as identity primary key,
  model text not null,
  variant text,
  cc integer,
  color text,
  stock integer not null default 1,
  status text not null default 'Available',
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.test_drives (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone_number text,
  vehicle_id bigint references public.test_drive_inventory(id),
  status text default 'Scheduled',
  date date,
  time text,
  license_number text,
  notes text,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.rc_records (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id),
  customer_name text not null,
  customer_phone text,
  vehicle_name text not null,
  status text default 'Pending',
  completed_at timestamptz,
  created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'staff' check (role in ('owner', 'staff')),
  created_at timestamptz default now()
);

-- 2. Add any missing columns just in case the tables already existed
alter table if exists public.inventory add column if not exists cc integer;
alter table if exists public.customers add column if not exists aadhaar_last4 text;
alter table if exists public.customers add column if not exists pan_masked text;
alter table if exists public.customers add column if not exists aadhaar_document_path text;
alter table if exists public.customers add column if not exists pan_document_path text;
alter table if exists public.sales add column if not exists invoice_number text;
alter table if exists public.sales add column if not exists signature_data text;
alter table if exists public.sales add column if not exists sale_type text default 'Sale';
alter table if exists public.sales add column if not exists old_vehicle_name text;
alter table if exists public.sales add column if not exists old_vehicle_registration text;
alter table if exists public.sales add column if not exists exchange_discount numeric default 0;
alter table if exists public.sales add column if not exists exchange_value numeric default 0;
alter table if exists public.sales add column if not exists rc_photo_path text;
alter table if exists public.sales add column if not exists updated_at timestamptz default now();
alter table if exists public.rc_records add column if not exists customer_phone text;
alter table if exists public.sales add column if not exists emi_amount numeric;
alter table if exists public.sales add column if not exists tenure_months integer;

-- 3. Enable RLS
alter table if exists public.inventory enable row level security;
alter table if exists public.customers enable row level security;
alter table if exists public.sales enable row level security;
alter table if exists public.test_drives enable row level security;
alter table if exists public.rc_records enable row level security;
alter table if exists public.test_drive_inventory enable row level security;
alter table if exists public.profiles enable row level security;

-- 4. Setup Auth Trigger
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_owner()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'); $$;

-- 5. Policies
drop policy if exists "Profiles self read" on public.profiles;
drop policy if exists "Owner reads profiles" on public.profiles;
create policy "Profiles self read" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Owner reads profiles" on public.profiles for select to authenticated using (id = auth.uid() or public.is_owner());

-- Broad MVP Policies (Allow all reads/writes for authenticated users)
drop policy if exists "MVP read inventory" on public.inventory;
drop policy if exists "MVP write inventory" on public.inventory;
create policy "MVP read inventory" on public.inventory for select to authenticated using (true);
create policy "MVP write inventory" on public.inventory for all to authenticated using (true) with check (true);

drop policy if exists "MVP read sales" on public.sales;
drop policy if exists "MVP write sales" on public.sales;
create policy "MVP read sales" on public.sales for select to authenticated using (true);
create policy "MVP write sales" on public.sales for all to authenticated using (true) with check (true);

drop policy if exists "MVP read customers" on public.customers;
drop policy if exists "MVP write customers" on public.customers;
create policy "MVP read customers" on public.customers for select to authenticated using (true);
create policy "MVP write customers" on public.customers for all to authenticated using (true) with check (true);

drop policy if exists "MVP read test drives" on public.test_drives;
drop policy if exists "MVP write test drives" on public.test_drives;
create policy "MVP read test drives" on public.test_drives for select to authenticated using (true);
create policy "MVP write test drives" on public.test_drives for all to authenticated using (true) with check (true);

drop policy if exists "MVP read RC records" on public.rc_records;
drop policy if exists "MVP write RC records" on public.rc_records;
create policy "MVP read RC records" on public.rc_records for select to authenticated using (true);
create policy "MVP write RC records" on public.rc_records for all to authenticated using (true) with check (true);

drop policy if exists "MVP read test drive inventory" on public.test_drive_inventory;
drop policy if exists "MVP write test drive inventory" on public.test_drive_inventory;
create policy "MVP read test drive inventory" on public.test_drive_inventory for select to authenticated using (true);
create policy "MVP write test drive inventory" on public.test_drive_inventory for all to authenticated using (true) with check (true);

-- 6. Storage Bucket
insert into storage.buckets (id, name, public)
values ('customer-documents', 'customer-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "Staff upload customer documents" on storage.objects;
drop policy if exists "Staff read customer documents" on storage.objects;
drop policy if exists "Staff delete customer documents" on storage.objects;
create policy "Staff upload customer documents" on storage.objects for insert to authenticated
with check (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Staff read customer documents" on storage.objects for select to authenticated
using (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Staff delete customer documents" on storage.objects for delete to authenticated
using (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);

-- 7. Seed Data
insert into public.test_drive_inventory (model, variant, cc, color, stock)
select * from (values
  ('Xtreme 125R', 'ABS', 125, 'Matte Red', 1),
  ('Xtreme 160R', '4V', 160, 'Sports Red', 1),
  ('Splendor+', 'XTEC 2.0', 100, 'Black', 1),
  ('Maverick 440', 'Base', 440, 'Phantom Black', 1),
  ('Pleasure+', 'XTEC', 110, 'Pearl White', 1)
) as demo(model, variant, cc, color, stock)
where not exists (
  select 1 from public.test_drive_inventory existing where existing.model = demo.model and existing.variant = demo.variant
);

insert into public.inventory (model, variant, cc, color, ex_showroom_price, on_road_price, max_discount, stock)
select * from (values
  ('Splendor+', 'XTEC 2.0', 100, 'Black', 82900::numeric, 98740::numeric, 3500::numeric, 8),
  ('Xtreme 125R', 'ABS', 125, 'Matte Red', 99500::numeric, 116890::numeric, 5000::numeric, 5),
  ('Xtreme 160R', '4V', 160, 'Sports Red', 120000::numeric, 142600::numeric, 7000::numeric, 4),
  ('Maverick 440', 'Base', 440, 'Phantom Black', 199000::numeric, 248600::numeric, 10000::numeric, 2),
  ('Pleasure+', 'XTEC', 110, 'Pearl White', 72000::numeric, 92450::numeric, 3000::numeric, 6),
  ('Glamour', 'Disc Brake', 125, 'Candy Red', 85000::numeric, 101500::numeric, 4000::numeric, 5)
) as seed(model, variant, cc, color, ex_showroom_price, on_road_price, max_discount, stock)
where not exists (
  select 1 from public.inventory existing where existing.model = seed.model and existing.variant = seed.variant
);

-- Note: We do not backfill sales/rc records in this script because a new project will have no sales history anyway.

-- Pending dues table for standalone udhaar
create table if not exists public.pending_dues (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text,
  amount numeric not null,
  status text not null default 'Pending',
  created_at timestamptz default now()
);
alter table if exists public.pending_dues enable row level security;

