-- RideFlow showroom setup for the current MVP.
-- Run this once in Supabase Dashboard -> SQL Editor.

-- Allow the Vite app (anon key) to read and write MVP records.
-- Replace these broad policies with authenticated staff policies before production.
alter table if exists public.inventory enable row level security;
alter table if exists public.inventory add column if not exists cc integer;
alter table if exists public.customers add column if not exists aadhaar_last4 text;
alter table if exists public.customers add column if not exists pan_masked text;
alter table if exists public.customers add column if not exists aadhaar_document_path text;
alter table if exists public.customers add column if not exists pan_document_path text;
alter table if exists public.sales add column if not exists invoice_number text;
alter table if exists public.sales add column if not exists signature_data text;
alter table if exists public.sales add column if not exists sale_type text default 'Sale';
alter table if exists public.sales add column if not exists old_vehicle_name text;
alter table if exists public.sales add column if not exists old_vehicle_registration text;
alter table if exists public.sales add column if not exists exchange_discount numeric default 0;
alter table if exists public.sales add column if not exists exchange_value numeric default 0;
alter table if exists public.sales add column if not exists rc_photo_path text;
alter table if exists public.sales add column if not exists updated_at timestamptz default now();
alter table if exists public.rc_records add column if not exists customer_phone text;
alter table if exists public.sales enable row level security;
alter table if exists public.customers enable row level security;
alter table if exists public.test_drives enable row level security;
alter table if exists public.rc_records enable row level security;

-- Dedicated bikes reserved for customer test drives. This is intentionally
-- separate from sale inventory, so a showroom can keep 4-5 demo units aside.
create table if not exists public.test_drive_inventory (
  id bigint generated by default as identity primary key,
  model text not null,
  variant text,
  cc integer,
  color text,
  stock integer not null default 1,
  status text not null default 'Available',
  created_at timestamptz default now()
);
alter table public.test_drive_inventory enable row level security;
drop policy if exists "MVP read test drive inventory" on public.test_drive_inventory;
drop policy if exists "MVP write test drive inventory" on public.test_drive_inventory;
create policy "MVP read test drive inventory" on public.test_drive_inventory for select to authenticated using (true);
create policy "MVP write test drive inventory" on public.test_drive_inventory for all to authenticated using (true) with check (true);

insert into public.test_drive_inventory (model, variant, cc, color, stock)
select * from (values
  ('Xtreme 125R', 'ABS', 125, 'Matte Red', 1),
  ('Xtreme 160R', '4V', 160, 'Sports Red', 1),
  ('Splendor+', 'XTEC 2.0', 100, 'Black', 1),
  ('Maverick 440', 'Base', 440, 'Phantom Black', 1),
  ('Pleasure+', 'XTEC', 110, 'Pearl White', 1)
) as demo(model, variant, cc, color, stock)
where not exists (
  select 1 from public.test_drive_inventory existing where existing.model = demo.model and existing.variant = demo.variant
);

-- Private KYC document storage. Files are never public; authenticated staff
-- can only access files inside their own user-id folder.
insert into storage.buckets (id, name, public)
values ('customer-documents', 'customer-documents', false)
on conflict (id) do update set public = false;

drop policy if exists "Staff upload customer documents" on storage.objects;
drop policy if exists "Staff read customer documents" on storage.objects;
drop policy if exists "Staff delete customer documents" on storage.objects;
create policy "Staff upload customer documents" on storage.objects for insert to authenticated
with check (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Staff read customer documents" on storage.objects for select to authenticated
using (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Staff delete customer documents" on storage.objects for delete to authenticated
using (bucket_id = 'customer-documents' and (storage.foldername(name))[1] = auth.uid()::text);

-- STAFF AUTH + ROLES
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'staff' check (role in ('owner', 'staff')),
  created_at timestamptz default now()
);
alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

drop policy if exists "Profiles self read" on public.profiles;
drop policy if exists "Owner reads profiles" on public.profiles;
create policy "Profiles self read" on public.profiles for select to authenticated using (id = auth.uid());

create or replace function public.is_owner()
returns boolean language sql security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'owner'); $$;

-- Avoid querying profiles from inside its own RLS policy. The security-definer
-- helper checks the current authenticated user's role safely.
drop policy if exists "Owner reads profiles" on public.profiles;
create policy "Owner reads profiles" on public.profiles for select to authenticated using (
  id = auth.uid() or public.is_owner()
);

drop policy if exists "MVP read inventory" on public.inventory;
drop policy if exists "MVP write inventory" on public.inventory;
create policy "MVP read inventory" on public.inventory for select to authenticated using (true);
create policy "MVP write inventory" on public.inventory for all to authenticated using (true) with check (true);

drop policy if exists "MVP read sales" on public.sales;
drop policy if exists "MVP write sales" on public.sales;
create policy "MVP read sales" on public.sales for select to authenticated using (true);
create policy "MVP write sales" on public.sales for all to authenticated using (true) with check (true);

drop policy if exists "MVP read customers" on public.customers;
drop policy if exists "MVP write customers" on public.customers;
create policy "MVP read customers" on public.customers for select to authenticated using (true);
create policy "MVP write customers" on public.customers for all to authenticated using (true) with check (true);

drop policy if exists "MVP read test drives" on public.test_drives;
drop policy if exists "MVP write test drives" on public.test_drives;
create policy "MVP read test drives" on public.test_drives for select to authenticated using (true);
create policy "MVP write test drives" on public.test_drives for all to authenticated using (true) with check (true);

drop policy if exists "MVP read RC records" on public.rc_records;
drop policy if exists "MVP write RC records" on public.rc_records;
create policy "MVP read RC records" on public.rc_records for select to authenticated using (true);
create policy "MVP write RC records" on public.rc_records for all to authenticated using (true) with check (true);

-- Starter inventory. Safe to run more than once: only adds models that are absent.
insert into public.inventory (model, variant, cc, color, ex_showroom_price, on_road_price, max_discount, stock)
select * from (values
  ('Destini Prime', 'Standard', 125, 'TBD', 71499::numeric, 85000::numeric, 3000::numeric, 5),
  ('Destini 125', 'Standard', 125, 'TBD', 80000::numeric, 95000::numeric, 3000::numeric, 5),
  ('Xoom', 'Standard', 111, 'TBD', 76000::numeric, 90000::numeric, 3000::numeric, 5),
  ('Xoom 125', 'Standard', 125, 'TBD', 85000::numeric, 100000::numeric, 3000::numeric, 5),
  ('Pleasure+ XTEC', 'Standard', 111, 'TBD', 78000::numeric, 92000::numeric, 3000::numeric, 5),
  ('Splendor+', 'Standard', 97, 'TBD', 75000::numeric, 89000::numeric, 2000::numeric, 5),
  ('Splendor+ XTEC', 'Standard', 97, 'TBD', 79000::numeric, 93000::numeric, 2000::numeric, 5),
  ('Splendor+ XTEC 2.0', 'Standard', 97, 'TBD', 82900::numeric, 98740::numeric, 3500::numeric, 8),
  ('Splendor+ Flex', 'Standard', 97, 'TBD', 85000::numeric, 100000::numeric, 2000::numeric, 5),
  ('Passion+', 'Standard', 97, 'TBD', 77000::numeric, 91000::numeric, 2000::numeric, 5),
  ('Passion XTEC', 'Standard', 113, 'TBD', 81000::numeric, 96000::numeric, 2000::numeric, 5),
  ('Super Splendor', 'Standard', 125, 'TBD', 80000::numeric, 95000::numeric, 3000::numeric, 5),
  ('Super Splendor XTEC', 'Standard', 125, 'TBD', 85000::numeric, 100000::numeric, 3000::numeric, 5),
  ('Glamour', 'Disc Brake', 125, 'TBD', 85000::numeric, 101500::numeric, 4000::numeric, 5),
  ('Glamour XTEC', 'Standard', 125, 'TBD', 89000::numeric, 105000::numeric, 4000::numeric, 5),
  ('Xtreme 125R', 'ABS', 125, 'TBD', 99500::numeric, 116890::numeric, 5000::numeric, 5),
  ('Xtreme 160R 4V', 'Standard', 163, 'TBD', 127000::numeric, 150000::numeric, 7000::numeric, 4),
  ('Xtreme 160R 2V', 'Standard', 163, 'TBD', 120000::numeric, 142600::numeric, 7000::numeric, 4),
  ('Xtreme 200S 4V', 'Standard', 200, 'TBD', 141000::numeric, 165000::numeric, 7000::numeric, 4),
  ('XPulse 200 4V', 'Standard', 200, 'TBD', 144000::numeric, 169000::numeric, 7000::numeric, 4),
  ('XPulse 200T 4V', 'Standard', 200, 'TBD', 140000::numeric, 164000::numeric, 7000::numeric, 4),
  ('Karizma XMR', 'Standard', 210, 'TBD', 179000::numeric, 210000::numeric, 10000::numeric, 3),
  ('Mavrick 440', 'Base', 440, 'TBD', 199000::numeric, 248600::numeric, 10000::numeric, 2)
) as seed(model, variant, cc, color, ex_showroom_price, on_road_price, max_discount, stock)
where not exists (
  select 1 from public.inventory existing where existing.model = seed.model and existing.variant = seed.variant
);

update public.inventory set cc = case model
  when 'Splendor+' then 100
  when 'Pleasure+' then 110
  when 'Xtreme 125R' then 125
  when 'Glamour' then 125
  when 'Xtreme 160R' then 160
  when 'Maverick 440' then 440
  else cc end
where cc is null;

-- Backfill customers and RC records for any sales already entered before this setup.
insert into public.customers (name, phone, created_at)
select distinct on (s.customer_name) s.customer_name, s.customer_phone, s.sale_date
from public.sales s
where not exists (
  select 1 from public.customers c where c.name = s.customer_name and coalesce(c.phone, '') = coalesce(s.customer_phone, '')
);

insert into public.rc_records (sale_id, customer_name, vehicle_name, status, created_at)
select s.id, s.customer_name, s.vehicle_name, 'Pending', s.sale_date
from public.sales s
where not exists (
  select 1 from public.rc_records r where r.sale_id = s.id
);

alter table if exists public.sales add column if not exists emi_amount numeric;
alter table if exists public.sales add column if not exists tenure_months integer;
alter table if exists public.sales add column if not exists amount_paid numeric default 0;

-- Pending dues table for standalone udhaar
create table if not exists public.pending_dues (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  customer_phone text,
  amount numeric not null,
  status text not null default 'Pending',
  created_at timestamptz default now()
);
alter table if exists public.pending_dues enable row level security;
